mode: vision # vision, calibration,
visualize: false
nav_topic: /robot/pose

cameras:
  - id: 0
    type: webcam
    stereo: false
    rate: 5 # Hz
    focal: [0.1, 0.1]
    center: [128, 128]
    near: 0.5
    far: 3.5

  # - id: 1
  #   type: thermal
  #   stereo: true
  #   rate: 10 # Hz
  #   focal: [0.2, 0.2]
  #   center: [256, 256]
  #   near: 1.0
  #   far: 5.0

models:
  - name: mobilenet
    type: 2d-detection
    path: /home/sam/models/mobilenet.caffemodel
    engine: opencv

  - name: midas
    type: depth
    path: /home/sam/models/dpt_next_vit_large_384.onnx
    engine: opencv

pose_estimation:
  depth_estimation: monocular
