mode: vision # vision, calibration
visualize: true
save_clouds: true
nav_topic: /robot/pose

cameras:
  - id: 0
    type: ros
    stereo: false
    rate: 10 # Hz
    img_size: [640, 480]
    focal: [381.4, 381.4]
    center: [320, 240]
    near: 0.5
    far: 3.5
    xyz: [0, 0, 0]
    quat: [0, 0, 0, 1] # (xyz w)

models:
  - name: mobilenet
    type: 2d-detection
    path: /home/sam/models/mobilenet.caffemodel
    engine: opencv

  - name: midas
    type: depth
    path: /home/sam/models/dpt_next_vit_large_384.onnx
    engine: opencv

object_detection:
  min_confidence: 0.75
  similar_detection: 0.7 # IoU threshold to check if bounding boxes are over the same object

pose_estimation:
  depth_estimation: monocular
