mode: vision # vision, calibration
visualize: true
nav_topic: /robot/pose

cameras:
  - id: 0
    type: webcam
    stereo: false
    rate: 5 # Hz
    img_size: [384, 384]
    focal: [0.1, 0.1]
    center: [128, 128]
    near: 0.5
    far: 3.5
    xyz: [0, 0, 0]
    quat: [0, 0, 0, 1] # (xyz w)

  # - id: 1
  #   type: thermal
  #   stereo: true
  #   rate: 10 # Hz
  #   focal: [0.2, 0.2]
  #   center: [256, 256]
  #   near: 1.0
  #   far: 5.0

models:
  - name: mobilenet
    type: 2d-detection
    path: /home/sam/models/mobilenet.caffemodel
    engine: opencv

  - name: midas
    type: depth
    path: /home/sam/models/dpt_next_vit_large_384.onnx
    engine: opencv

object_detection:
  min_confidence: 0.75
  similar_detection: 0.7 # IoU threshold to check if bounding boxes are over the same object

pose_estimation:
  depth_estimation: monocular
