camera:
  type: webcam
  stereo: false
  rate: 5 # Hz
  visualize: true

models:
  - name: mobilenet
    type: 2d-detection
    path: /home/sam/models/mobilenet.caffemodel
    engine: opencv

pose_estimation:
  depth_estimation: monocular
