mode: vision # vision, calibration
visualize: true
save_clouds: true
nav_topic: /robot/pose

cameras:
  #- file: usbCamera.yaml
  - file: realSenseCamera_d435i.yaml

models:
  - name: mobilenet
    type: 2d-detection
    path: /home/sam/models/mobilenet.caffemodel
    engine: opencv

  - name: midas
    type: depth
    path: /home/sam/models/dpt_next_vit_large_384.onnx
    engine: opencv

object_detection:
  min_confidence: 0.75
  similar_detection: 0.7 # IoU threshold to check if bounding boxes are over the same object

pose_estimation:
  depth_estimation: monocular
